### ISSUE TITLE
install-nexus.sh

### ISSUE THREAD

**Issue by paulvi** [rgl/nexus-vagrant#2]
This is rough to understand (for example how `nexus3` appears in provision.sh).

However this is great amount of work done. That could be huge time saving for those who need to install nexus.

Would you mind make part for installing nexus more clear (easy for discovery, for example in separate repository or at least in separate file)

**Comment by rgl** [comment]
In https://github.com/rgl/nexus-vagrant/commit/d48c75bdbf186d57276db28aff1abc5c7238a9c3 I've moved the nexus installation to a different script file. Re-open this issue if this is not enough.
